### ISSUE TITLE
primo (private monero payments)

### ISSUE THREAD

**Issue by selene-kovri** [monero-ecosystem/meta#47] opened 2019-07-25 13:29 UTC
Hi,

I've just released software for monero, see:
https://github.com/selene-kovri/primo-apache
https://github.com/selene-kovri/primo-firefox
https://github.com/selene-kovri/primo-control-center

Is this the kind of thing you're after ? I2P IRC is dead so I can't even tell the good Monero people about it, so moving it to this monero-ecosystem place seems like the next best thing :)

**Comment by erciccione** [comment] 2019-07-26 10:14
Hi @selene-kovri, thanks for reaching out. Sorry to hear i2p IRC is not working. It used to be used by a couple of people until not long a go, i will ask around if anybody know something about it.

About the projects: if i got them right, they are all based on web mining monero. The problem is that after RandomX web mining will be even less feasable than now, and i don't know if your projects would be usable. What's your opinion on that?

Also, you are proposing to add all three, but they are all part of a main project ("Primo"). Could you clarify how the 3 are related to each other and what are mid-term and long tearm goals? Is it necessary to have 3 different repos or they could be unified in just one?

I think the project is interesting and it's worth to take a deeper look at it. Pinging the other @monero-ecosystem/maintainers , would be great to have an opinion on this.

I would wait before starting the actual voting, better to have the concerns clarified first so that we have a clear idea of what we are voting on, but i  encourage the Members to voice their opinion.

**Comment by erciccione** [comment] 2019-07-26 10:29
@dEBRUYNE-1 righfully pointed out that i could be wrong about this: `i could be wrong about this: `after RandomX web mining will be even less feasable than now`. if somebody else could clarify that, would be great`. Waiting for somebody able to clarify. @hyc or @sech1 maybe?

**Comment by selene-kovri** [comment] 2019-07-26 10:33
It's not what you call "web mining" I think. The mining is done by a native miner, not some Javascript code in the browser. The code that runs in the browser is only a thin layer that acts as glue between the website and the Qt UI. In theory, the native miner can run full speed, though it is currently a single thread.

My goals are to have other people start contributing to this since I sinked a lot of time into this and I have to catch up on things I've neglected while doing so. I wanted to have something that actually works first. If would also be nice to get some people to start using it, but it's a bit chicken and egg, a website only has an incentive if there are users, but a user only needs this is there are websites :) Still, the "optional" configuration can maybe help with that. We'll see :)

**Comment by rbrunner7** [comment] 2019-07-26 11:00
I am not sure but I think the daemon extension that you rely on (see https://github.com/monero-project/monero/pull/5357) has seen quite some changes lately as it was going through review and refinement. Did you follow that? Is your software still compatible with the latest version of that PR?

**Comment by selene-kovri** [comment] 2019-07-26 11:09
I don't know yet, but it will be :)

**Comment by erciccione** [comment] 2019-07-28 13:16
So, since there are no further comments, we can start the vote for adding Primo to the Ecosystem @monero-ecosystem/maintainers. As said in the comments above, the 3 repos will be unified in just one, and that one would be added to the Ecosystem.

**Comment by erciccione** [comment] 2019-07-28 13:23
I tend to be positive about this project. I really like that somebody started building on top of monero-project/monero#5357 because that's a feature i think could have a big positive inpact on how Monero is used and could potentially give the kick to start small business based on Monero.

Beside that, i think it's fundamental that this project is constantly maintained if it want to be succesful and i hope the Ecosystem and the Monero community in general can help with that.

To conclude, i agree with adding this to the Ecosystem, but given that the repository will be kept alive and updated. Before adding it, i would prefer Primo to be syncronized with the present state of  monero-project/monero#5357.

**Comment by selene-kovri** [comment] 2019-07-30 11:47
> Is your software still compatible with the latest version of that PR?

No changes were needed, it works well with the latest version of that PR.

**Comment by erciccione** [comment] 2019-08-09 10:11
@selene-kovri Could you merge the 3 projects in one single repo as said? so that our members/maintainers have a clear idea of what is going to be added to the Ecosystem.

**Comment by selene-kovri** [comment] 2019-08-10 19:17
They already are.

**Comment by erciccione** [comment] 2019-08-23 10:22
@selene-kovri I still see `primo-apache`, `primo-firefox` and `primo-control-center` in three different repos. Am i missing something?

**Comment by erciccione** [comment] 2019-08-23 20:50
Ok, the repo of the 3 projects merged together is here: https://github.com/selene-kovri/primo

**Comment by Gingeropolous** [comment] 2019-09-01 04:25
this is very cool.  I'm curious how I can set this up. One of these days, with all my free time...

**Comment by erciccione** [comment] 2019-09-16 08:34
@monero-ecosystem/maintainers What do you think about this project? should be added or not?

I personally am in favour of adding Primo, but we need more opinions from the members of the Ecosystem.

**Comment by el00ruobuob** [comment] 2019-09-16 09:03
I'm not a maintainer, but I vote in favor.

**Comment by rbrunner7** [comment] 2019-09-16 09:15
I not a maintainer likewise, but would also vote in favor.

**Comment by Jh49211** [comment] 2019-09-16 12:01
I love the simplicity of Primo and think that it will great addition if
done correctly; With that being said we need to make sure that it is
compatible with a basic wallet to allow a better UX.

**Comment by Lafudoci** [comment] 2019-09-18 02:30
Yes, let's add them into the ecosystem :)

**Comment by normoes** [comment] 2019-09-18 04:49
I also think, that's a very good project to add..

**Comment by erciccione** [comment] 2019-09-18 09:46
Thanks everybody for your comments. We have a clear consensus, we can transfer Primo to the Monero Ecosystem :)

Congratulation @selene-kovri, now we need to transfer the repo. I sent you an invitation to become member of the Ecosystem project, you need to accept that before being able to do the transfer.

**Comment by erciccione** [comment] 2019-09-26 17:21
ping @selene-kovri

**Comment by erciccione** [comment] 2019-10-07 09:37
@selene-kovri wrote me yesterday on `#monero`. Appearently GitHub kicked her out for some reason and she is not able to log in again. She decided to drop it and use GitLab instead. The Primo repository is now here: https://repo.getmonero.org/selene/primo

Since Primo cannot be moved to the Ecosystem project anymore, i'm closing this issue.

**Closed** 2019-10-07 09:38 UTC
Labels: Approved, Repo proposal, consensus
