### ISSUE TITLE
Handover of PiNode-XMR to the community

### ISSUE THREAD

**Issue by shermand100** [monero-ecosystem/meta#37] opened 2019-05-20 21:08 UTC
I think the Monero community would benefit greatly from a plug and play Full node that can run on a small low power device 24/7 such as the Raspberry Pi (other boards can easily be adapted to from this project). 
It would be a great asset for a user to run their own node they can trust and connect to for making transactions as Privately as possible.

I've built the foundations for this but am at my technical limit, I still want to continue developing it but need the help of others for it to reach it's potential. 

It currently is at a stage where it runs the full node and feeds back statistics to a web-ui with details on connected nodes, transactions and sync status, all plug and play to that point. 

Development is needed to make it suitable for external connections, user buttons for simple/common features. Configuration for the static IP. And a first boot menu for password setting. All of which I'm sure are simple projects for our community.

More info on the project here:
https://www.pinode.co.uk/monero-plug-and-play.html

Github:
https://github.com/shermand100/pinode-xmr

(And if anyone is familiar with raspiblitz for Bitcoin Lightning this is my target for quality/simplicity for basic users I would like to aim for https://github.com/rootzoll/raspiblitz I don't think it will take too much more to get that standard)

**Comment by erciccione** [comment] 2019-05-22 10:36
Hi @shermand100, thanks the project is interesting. If i understood, you are looking for somebody to help you with the development of the project here on the Ecosystem. That's actually great and one of the reason this project was created.

What skills should a maintainer have to help you with this project? What need to be done?

@monero-ecosystem/maintainers one of you might be interested?

**Comment by Lafudoci** [comment] 2019-05-22 12:48
@Jasonhcwong has a related project [monerobox](https://github.com/monero-ecosystem/monerobox) within ecosystem, maybe you could consider to collaborate. Find a way to combine these resources for an similar goal would be a good step.

**Comment by erciccione** [comment] 2019-05-22 12:53
> maybe you could consider to collaborate

I don't know the differences between the two projects, but if they are similar enough, this sounds like the best solution to me.

**Comment by shermand100** [comment] 2019-05-22 13:28
They are similar projects but currently operate on different hardware. I'd like the stick with the Raspberry Pi device as it's cost and availability are attractive and raspberry-pi org have been very predictable with backwards compatibility of devices assuming this will continue as they release more powerful models.

I spoke with Jasonhcwong about 3 months ago via reddit and we had slightly different directions, but since the release of raspiblitz for bitcoin and Litecoin I'd really like to focus 100% on just Monero, if he'd reconsider and collaborate I'm sure something positive would result. 

For the continued development of this PiNode-XMR project the first simple task is for someone with a basic grasp of php ajax to simply link user buttons in advanced-settings.html to their respective bash scripts to enable interaction.

I'm currently working on a whiptail boot menu for setting passwords to enable linking a users moneroj wallet to their home node to spend monero out in the wild.

**Comment by erciccione** [comment] 2019-06-17 09:15
@shermand100 I suggest to post on reddit.com/r/monero asking for feeback. Much wider audience there.

**Comment by dginovker** [comment] 2019-09-25 01:26
The project is still being kept up to date and is rather neat I find. It's different enough from MoneroBox in some cases and provides people with options between the two. If OP still wants to merge, I support this proposal.

**Comment by erciccione** [comment] 2019-09-25 15:58
@dginovker the problem is that @shermand100 is proposing to hand over the repository to the community and to have this in the ecosystem it would first need a maintainer willing to work on it.

**Comment by shermand100** [comment] 2019-09-25 16:58
@erciccione To clarify, this is and still will be my main project to develop. However this is my first project I've undertaken from the ground up, and at each step I have had to learn how each component works and trial and error solve fixes. As I add more features which require more complex scripts and configurations I don't believe I currently have the experience required to produce the quality end result in a realistic timeframe. (I'm an aircraft mechanic by trade and do this as a hobby) There may also be better practices the things which I am unaware of.

To include this in the ecosystem I hope would interest others to contribute who do have this experience. At the very least scrutinize what I have so far done. 

With a mentor or collaborator this project can develop safely, faster.

**Comment by Lafudoci** [comment] 2020-04-08 03:32
> @erciccione To clarify, this is and still will be my main project to develop. However this is my first project I've undertaken from the ground up, and at each step I have had to learn how each component works and trial and error solve fixes. As I add more features which require more complex scripts and configurations I don't believe I currently have the experience required to produce the quality end result in a realistic time frame. (I'm an aircraft mechanic by trade and do this as a hobby) There may also be better practices for things which I am unaware of.
>
> To include this in the ecosystem I hope would interest others to contribute who do have this experience. At the very least scrutinise what I have so far done.
> 
> With a mentor or collaborator this project can develop safely, faster.
> 

Don't worry. It is exactly how open-sourced project works. Everyone can contribute and the philosophy is "Release early, release often". It's not necessary to release the project with perfect coding. The most important thing is it works and it could help/inspire/benefit someone in the community. We can always make it better later. From my perspective, this PiNode project is definitely already a nice project for the community.

> One last loose end...
> For initial development speed the Web UI is from a free template:
> 
> https://github.com/designmodo/Flat-UI
> 
> Which contains over 2000 objects, most of which are not required for PiNode-XMR. This extra bloat is not great for transparency and the overall open source target of the project. I have appealed for help from the Monero community and will see what response I get for new designs that are better audit-able. I do feel though that a barrier for offers of help may be that this is still my project and not a community one.

In my opinion, it doesn't really matter. The point of ecosystem for me is a place to sharing works rather than a certification process. The users always need to take their risk of utilizing open-sourced codes.

@erciccione  This project is actively developing and well-documented. It is promising for letting people build a Monero node easily on the Raspberry Pi board. I'd like to vote yes for including this project in the ecosystem.

**Comment by erciccione** [comment] 2020-04-08 09:16
@Lafudoci I agree that this would be a great addition to the Ecosystem, i think the process here got stuck because i was under the impression that handeover the project was part of the proposal. If it's not IMHO we can go ahead and add this.

@shermand100 what are your thoughts?

**Comment by shermand100** [comment] 2020-04-08 13:18
@erciccione Handover was the wrong phrase. I will still be the lead on this and will continue developing it.

**Comment by erciccione** [comment] 2020-04-08 15:59
Then i don't see any issue.

Let's see if somebody else from @monero-ecosystem/maintainers have an opinion, otherwise i think we can just go ahead and start the transfer.

**Comment by erciccione** [comment] 2020-04-11 11:04
We can consider it approved then. @shermand100 I sent you an invitation to join the the project, please accept it and then transfer the repo :)

**Comment by shermand100** [comment] 2020-04-11 18:03
@erciccione . Accepted and repo transferred. It will take a little time to amend all the installation links to the new Repo. 
Once complete I'll remove my personal repository to avoid confusion with this version.

Thanks very much for the inclusion.

**Comment by erciccione** [comment] 2020-04-28 10:16
Please review https://github.com/monero-ecosystem/meta/pull/68. I will merge it soon anyway, since the addition was already discussed and approved here.

**Comment by Lafudoci** [comment] 2020-04-28 10:26
@shermand100 You are also welcome to make your project page on the [Monero Ecosystem](https://moneroecosystem.org/) website. The guide is in the [repo README](https://github.com/monero-ecosystem/monero-ecosystem.github.io).

**Comment by erciccione** [comment] 2020-05-13 08:33
@shermand100 i added it for you: https://github.com/monero-ecosystem/monero-ecosystem.github.io/pull/17

After that's merged we cann announce it.

**Comment by erciccione** [comment] 2020-05-21 11:49
Announced [on Reddit](https://www.reddit.com/r/Monero/comments/gnvdmz/a_new_project_joins_the_monero_ecosystem/) and [Twitter](https://twitter.com/calciferciccio/status/1263436444623912961).

Thanks everybody :)

**Closed** 2020-05-21 11:49 UTC
Labels: Approved, Repo proposal, consensus
